name: Run Preprocessing Automatically

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "IMDB_raw/IMDB_raw.csv"
      - "preprocessing/automate_Advent-Road-Marly.py"

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib seaborn scikit-learn scipy nltk gensim

      - name: Download NLTK data
        run: |
          python -m nltk.downloader punkt stopwords wordnet omw-1.4

      - name: List files for debugging
        run: ls -R

      - name: Run preprocessing script
        run: python preprocessing/automate_Advent-Road-Marly.py

      - name: Upload processed dataset
        uses: actions/upload-artifact@v4
        with:
          name: IMDB_preprocessing
          path: "preprocessing/IMDB_preprocessing.csv"
